export default [
  {
    id: 0,
    title: 'სააგენტოს თავმჯდომარე',
    name: 'ნოდარ ხადური',
    tel: '0322 440-770 (21-74)',
    email: ['chairman@competition.ge', 'info-gca@competition.ge'],
    parentId: '',
  },
  {
    id: 1,
    title: 'თავმჯდომარის პირველი მოადგილე',
    name: 'დავით ჭიჭინაძე',
    tel: '0322 440-770 (24-65)',
    email: ['dchichinadze@competition.ge'],
    parentId: '0',
  },
  {
    id: 2,
    title: 'თავმჯდომარის მოადგილე',
    name: 'გიორგი ფერაძე',
    tel: '0322 440-770 (24-23)',
    email: ['gperadze@competition.ge'],
    parentId: '0',
  },
  {
    id: 3,
    title: 'ეკონომიკური კონკურენციის დაცვის დეპარტამენტის უფროსი',
    name: 'სლავა ფეტელავა',
    tel: '0322 440-770 (24-61)',
    email: ['sfetelava@competition.ge'],
    parentId: '0',
  },
  {
    id: 4,
    title: 'იურიდიული დეპარტამენტის უფროსი',
    name: 'სოფიო მომცელიძე',
    tel: '0322 440-770 (24-62)',
    email: ['Smomtselidze@competition.ge'],
    parentId: '1',
  },
  {
    id: 5,
    title: 'ბაზრის მონიტორინგისა და ანალიზის დეპარტამენტის უფროსი',
    name: 'ნატო	კაკაურიძე',
    tel: '0322 440-770 (24-68)',
    email: ['nkakauridze@competition.ge'],
    parentId: '2',
  },
  {
    id: 6,
    title: 'ადმინისტრაციული დეპარტამენტის უფროსი',
    name: 'რევაზ	კავთელიშვილი',
    tel: '0322 440-770 (20-75)',
    email: ['rkavtelishvili@competition.ge'],
    parentId: '2',
  },
  {
    id: 7,
    title: 'საზოგადოებასთან ურთიერთობების მენეჯერი',
    name: 'ხატია 	წიკლაური',
    tel: '0322 440-770 (24-64)',
    email: ['ktsiklauri@competition.ge'],
    parentId: '2',
  },
  {
    id: 8,
    title: 'საერთაშორისო ურთიერთობების მენეჯერი',
    name: 'თეონა დეკანოსიძე',
    tel: '0322 440-770 (24-67)',
    email: ['tdekanosidze@competition.ge '],
    parentId: '1',
  },
];
